### ISSUE TITLE
add arduino MKR1000 JSON and create tickets for apps

### ISSUE THREAD

**Issue by blynkkk** [blynkkk/boards#1]

**Comment by aethaniel** [comment]
Hi @blynkkk, I would like to contribute on a similar way by adding Arduino Zero and some similar boards from Atmel. 
Unfortunately, I didn't find enough information about the board json file format and how to fully add a new board support in https://github.com/blynkkk/blynk-library.

Can you point me to the proper information, please?

**Comment by doom369** [comment]
@blynkkk this board is already added and tickets for app not needed any more. I explained you this recently.

@aethaniel cool, we don't have any information about making those jsons, but it's structure is very self-descriptive. Isn't it?

**Comment by aethaniel** [comment]
@doom369, i had some doubts about that kind of line: "ops": [ "dr", "dw" ] but indeed, it is pretty clear after some thoughts.

I see new boards are added in 'debug' subfolder. Can I guess they are moved to root folder once fully validated? ie, do I have to create my new boards in debug subfolder and submit my patch?

**Comment by doom369** [comment]
@aethaniel 

> i had some doubts about that kind of line: "ops": [ "dr", "dw" ] but indeed, it is pretty clear after some thoughts.

=). nice

> Can I guess they are moved to root folder once fully validated?

Exactly. The main problem during tests is real hardware that we usually have to buy and deliver. That takes some time. But we also rely on community feedback.

> do I have I create my new boards in debug subfolder and submit my patch?

Yes please.
