### ISSUE TITLE
Add letters to Generic Board pins

### ISSUE THREAD

**Issue by blynkkk** [blynkkk/boards#2]
Right now it's impossible to distinguish between Analog and Digital pins

**Comment by vshymanskyy** [comment]
It's impossible - Generic Boards have no analog pins.
Only analog output (PWM) - but that's digital.

**Comment by vshymanskyy** [comment]
Okay, I may be wrong - we had added it ;)

**Comment by blynkkk** [comment]
BTW, accordingly to rules, only person who created the ticket can close it.

**Comment by vshymanskyy** [comment]
@doom369 is it possible that this change breaks all Generic projects with set pins?

**Comment by doom369** [comment]
@vshymanskyy this is possible. But according to stats we have only few users (1%) with generic boards. So I think this is not a problem.

**Comment by doom369** [comment]
@alexkipar @aashvetsov what do you think?

**Comment by aashvetsov** [comment]
@doom369 My opinion is that according to the statistics this is not a big problem.
