### ISSUE TITLE
Relation between boards repo and blynk server

### ISSUE THREAD

**Issue by aethaniel** [blynkkk/boards#7]
Hi, 
Is the boards repo used by blynk server?

For my classes, I'm using a custom server on a RasbPi and would like to be able to limit only to the boards we use there. Is it possible?

**Comment by doom369** [comment]
Hi. Boards not used by the server, only by clients.

**Comment by aethaniel** [comment]
Thanks @doom369, I was hoping to be able to customize the boards list appearing on the students smartphones using the Blynk app.

Considering your answer, it seems not to be possible. Do you confirm?

**Comment by doom369** [comment]
Yes. This is not possible at the moment.
